/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_elektrik_veritabani;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABRA
 */
public class MusteriEkran extends javax.swing.JFrame {
    
    static final String DB_URL = "jdbc:oracle:thin:@//localhost:1521/XEPDB1";
    static final String USER = "SYSTEM";
    static final String PASS = "ankaramessi78";
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
   public void Connect(){
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection(DB_URL,USER,PASS);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Proje_Elektrik_Veritabani.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 3");
        } catch (SQLException ex) {
            Logger.getLogger(Proje_Elektrik_Veritabani.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 4");
        }
   }
    
    
    /**
     * Creates new form MusteriEkran
     */
    String musteri_no,musteri_isim,musteri_soyisim,musteri_cins,musteri_sehir,musteri_ilce,musteri_faturadate,musteri_statu,musteri_sifre;
    int musteri_gecenyil, musteri_fatura;
    public MusteriEkran(String no,String ad,String soyad,String cinsi,String sehir, String ilce, int gecenyil, int fatura, String kalanzaman, String status, String sifre) {
        Connect();
        initComponents();
        this.setLocationRelativeTo(null);
        numara.setText(no);
        isim.setText(ad);
        soyisim.setText(soyad);
        sehir_label.setText(sehir);
        ilce_label.setText(ilce);
        fatura_label.setText("" + fatura);
        if(kalanzaman == null || fatura == 0)
            date_label.setVisible(false);
        else
            date_label.setText(kalanzaman);
        this.musteri_no = no;
        this.musteri_isim = ad;
        this.musteri_soyisim = soyad;
        this.musteri_cins = cinsi;
        this.musteri_sehir = sehir;
        this.musteri_ilce = ilce;
        this.musteri_gecenyil = gecenyil;
        this.musteri_fatura = fatura;
        this.musteri_faturadate = kalanzaman;
        this.musteri_statu = status;
        this.musteri_sifre = sifre;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mevcutSifre = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        yeniSifre = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        tekrarYeniSifre = new javax.swing.JPasswordField();
        sifredegis_button = new java.awt.Button();
        numara = new javax.swing.JLabel();
        isim = new javax.swing.JLabel();
        soyisim = new javax.swing.JLabel();
        sehir_label = new javax.swing.JLabel();
        ilce_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fatura_label = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fatura_öde = new java.awt.Button();
        cikis_yap = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(92, 60, 146));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(92, 60, 146));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(162, 213, 198));
        jLabel1.setText("Müşteri Ekranı");

        jPanel2.setBackground(new java.awt.Color(7, 123, 138));

        jLabel2.setBackground(new java.awt.Color(162, 213, 198));
        jLabel2.setForeground(new java.awt.Color(162, 213, 198));
        jLabel2.setText("Bilgileriniz");

        jLabel3.setForeground(new java.awt.Color(162, 213, 198));
        jLabel3.setText("İsim:");

        jLabel4.setForeground(new java.awt.Color(162, 213, 198));
        jLabel4.setText("Soyisim:");

        jLabel5.setForeground(new java.awt.Color(162, 213, 198));
        jLabel5.setText("Numara:");

        jLabel6.setForeground(new java.awt.Color(162, 213, 198));
        jLabel6.setText("Şehir:");

        jLabel7.setForeground(new java.awt.Color(162, 213, 198));
        jLabel7.setText("İlçe:");

        jLabel8.setForeground(new java.awt.Color(162, 213, 198));
        jLabel8.setText("Mevcut Şifre:");

        jLabel9.setForeground(new java.awt.Color(162, 213, 198));
        jLabel9.setText("Yeni Şifre:");

        jLabel10.setForeground(new java.awt.Color(162, 213, 198));
        jLabel10.setText("Yeni Şifre Tekrar:");

        sifredegis_button.setBackground(new java.awt.Color(215, 38, 49));
        sifredegis_button.setLabel("Şifre Değiştirme");
        sifredegis_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifredegis_buttonActionPerformed(evt);
            }
        });

        numara.setBackground(new java.awt.Color(162, 213, 198));
        numara.setForeground(new java.awt.Color(162, 213, 198));
        numara.setText("jLabel11");

        isim.setForeground(new java.awt.Color(162, 213, 198));
        isim.setText("jLabel12");

        soyisim.setForeground(new java.awt.Color(162, 213, 198));
        soyisim.setText("jLabel13");

        sehir_label.setForeground(new java.awt.Color(162, 213, 198));
        sehir_label.setText("jLabel14");

        ilce_label.setForeground(new java.awt.Color(162, 213, 198));
        ilce_label.setText("jLabel15");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numara)
                            .addComponent(isim)
                            .addComponent(soyisim)
                            .addComponent(sehir_label)
                            .addComponent(ilce_label))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yeniSifre)
                            .addComponent(mevcutSifre)
                            .addComponent(tekrarYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sifredegis_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numara))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isim))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(soyisim))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sehir_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ilce_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mevcutSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tekrarYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(sifredegis_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel3.setBackground(new java.awt.Color(7, 123, 138));

        jLabel16.setBackground(new java.awt.Color(162, 213, 198));
        jLabel16.setForeground(new java.awt.Color(162, 213, 198));
        jLabel16.setText("Faturanız");

        fatura_label.setBackground(new java.awt.Color(162, 213, 198));
        fatura_label.setForeground(new java.awt.Color(162, 213, 198));
        fatura_label.setText("jLabel11");

        jLabel19.setForeground(new java.awt.Color(162, 213, 198));
        jLabel19.setText("Fatura Tarihi:");

        date_label.setForeground(new java.awt.Color(162, 213, 198));
        date_label.setText("jLabel12");

        jLabel17.setForeground(new java.awt.Color(162, 213, 198));
        jLabel17.setText("Fatura Miktarı:");

        fatura_öde.setActionCommand("Fatura Öde");
        fatura_öde.setBackground(new java.awt.Color(215, 38, 49));
        fatura_öde.setLabel("Fatura Öde");
        fatura_öde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatura_ödeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatura_label)
                    .addComponent(date_label))
                .addGap(99, 99, 99))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(fatura_öde, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(fatura_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(date_label))
                .addGap(54, 54, 54)
                .addComponent(fatura_öde, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cikis_yap.setActionCommand("Çıkış Yap");
        cikis_yap.setBackground(new java.awt.Color(215, 38, 49));
        cikis_yap.setLabel("Çıkış Yap");
        cikis_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_yapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cikis_yap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cikis_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifredegis_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifredegis_buttonActionPerformed

            if(mevcutSifre.getText().equals(musteri_sifre)){
                if(yeniSifre.getText().equals(tekrarYeniSifre.getText())){
                    musteri_sifre = yeniSifre.getText();
                    try{
                    String msql = "update musteri set sifre = ? where clientNo = ?";
                     pst = con.prepareStatement(msql);
                    pst.setString(1, musteri_sifre);
                    pst.setString(2, musteri_no);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Şifreniz başarıyla yenilenmiştir.");
                     MusteriEkran sayfayenileme = new MusteriEkran(musteri_no,musteri_isim,musteri_soyisim,musteri_cins,musteri_sehir,musteri_ilce,musteri_gecenyil,musteri_fatura,musteri_faturadate,musteri_statu,musteri_sifre);
                    sayfayenileme.setVisible(true);
                    this.dispose();
                    }catch (SQLException ex) {
                     Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("Hata Burada 311111");
                    }
                }else
                    JOptionPane.showMessageDialog(this,"Yeni şifre ve tekrarı aynı olmalıdır.");
                
            }else{
                System.out.println(musteri_sifre + " " + mevcutSifre.getText());
                JOptionPane.showMessageDialog(this,"Mevcut şifre yanlış girilmiştir.");}
    }//GEN-LAST:event_sifredegis_buttonActionPerformed

    private void fatura_ödeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatura_ödeActionPerformed
        if(musteri_fatura == 0){
            JOptionPane.showMessageDialog(this,"Ödenmesi gereken herhangi bir faturanız bulunmamaktadır.");
        }else{
        this.musteri_fatura = 0;
        fatura_label.setText(""+musteri_fatura);
        System.out.println(musteri_no);
        try{
            String msql = "update musteri set billQuantity = ?, lastDate = ? where clientNo = ?";
            pst = con.prepareStatement(msql);
            pst.setInt(1, musteri_fatura);
            pst.setString(2, null);
            pst.setString(3, musteri_no);
            pst.executeUpdate();
            MusteriEkran sayfayenileme = new MusteriEkran(musteri_no,musteri_isim,musteri_soyisim,musteri_cins,musteri_sehir,musteri_ilce,musteri_gecenyil,musteri_fatura,musteri_faturadate,musteri_statu,musteri_sifre);
            sayfayenileme.setVisible(true);
            this.dispose();
        }catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 311111");
            }
        
        }
    }//GEN-LAST:event_fatura_ödeActionPerformed

    private void cikis_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_yapActionPerformed
        Giris giris = new Giris();
        giris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cikis_yapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cikis_yap;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel fatura_label;
    private java.awt.Button fatura_öde;
    private javax.swing.JLabel ilce_label;
    private javax.swing.JLabel isim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField mevcutSifre;
    private javax.swing.JLabel numara;
    private javax.swing.JLabel sehir_label;
    private java.awt.Button sifredegis_button;
    private javax.swing.JLabel soyisim;
    private javax.swing.JPasswordField tekrarYeniSifre;
    private javax.swing.JPasswordField yeniSifre;
    // End of variables declaration//GEN-END:variables
}
