/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_elektrik_veritabani;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABRA
 */
public class PersonelEkran extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:oracle:thin:@//localhost:1521/XEPDB1";
    static final String USER = "SYSTEM";
    static final String PASS = "ankaramessi78";
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
   public void Connect(){
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection(DB_URL,USER,PASS);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Proje_Elektrik_Veritabani.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada");
        } catch (SQLException ex) {
            Logger.getLogger(Proje_Elektrik_Veritabani.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada");
        }
   }
    
    private String personel_isim,personel_soyisim,cinsiyet,no,sehir,sifre;
    public PersonelEkran(String ad, String soyad, String gender, String city, String no, String sifre) {
        Connect();
        initComponents();
        this.setLocationRelativeTo(null);
        this.personel_isim = ad;
        personelAd.setText(personel_isim);
        this.personel_soyisim = soyad;
        personelSoyad.setText(personel_soyisim);
        this.cinsiyet = gender;
        this.no = no;
        personelNo.setText(this.no);
        this.sehir = city;
        personelSehir.setText(sehir);
        this.sifre = sifre;
        ad_degis.setVisible(false);
        soyad_degis.setVisible(false);
        sehir_degis.setVisible(false);  
        MusteriTable();
    }
    
    public void MusteriTable(){
         try {
            pst = con.prepareStatement("select * from musteri where mCity = ?");
            pst.setString(1, sehir);
            rs = pst.executeQuery();
            ResultSetMetaData Rsm = rs.getMetaData();
            int c;
            c = Rsm.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable2.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                
                for(int i  = 1; i<= c ;i++){
                v2.add(rs.getString("clientNo"));
                v2.add(rs.getString("fName"));
                v2.add(rs.getString("lName"));
                v2.add(rs.getString("gender"));
                v2.add(rs.getString("mCity"));
                v2.add(rs.getString("street"));
                v2.add(rs.getString("billQuantity"));
                v2.add(rs.getString("lastDate"));
                v2.add(rs.getString("status"));
                }
                df.addRow(v2);
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        personelAd = new javax.swing.JLabel();
        personelSoyad = new javax.swing.JLabel();
        personelSehir = new javax.swing.JLabel();
        personelNo = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        sifredegis_button = new java.awt.Button();
        ad_degis = new javax.swing.JTextField();
        soyad_degis = new javax.swing.JTextField();
        sehir_degis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mevcutSifre = new javax.swing.JPasswordField();
        yeniSifre = new javax.swing.JPasswordField();
        tekrarYeniSifre = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        fatura_button = new java.awt.Button();
        musteri_ekle = new java.awt.Button();
        musteri_sil = new java.awt.Button();
        cikis_yap = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(92, 60, 146));

        jLabel1.setBackground(new java.awt.Color(92, 60, 146));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(162, 213, 198));
        jLabel1.setText("Çalışan Ekranı");

        jPanel2.setBackground(new java.awt.Color(7, 123, 138));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 213, 198));
        jLabel2.setText("Bilgileriniz");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(162, 213, 198));
        jLabel3.setText("Ad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(162, 213, 198));
        jLabel4.setText("Soyad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(162, 213, 198));
        jLabel5.setText("Şehir:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(162, 213, 198));
        jLabel6.setText("Numara:");

        personelAd.setForeground(new java.awt.Color(162, 213, 198));
        personelAd.setText("jLabel7");

        personelSoyad.setForeground(new java.awt.Color(162, 213, 198));
        personelSoyad.setText("jLabel8");

        personelSehir.setForeground(new java.awt.Color(162, 213, 198));
        personelSehir.setText("jLabel9");

        personelNo.setForeground(new java.awt.Color(162, 213, 198));
        personelNo.setText("jLabel10");

        button1.setBackground(new java.awt.Color(215, 38, 49));
        button1.setLabel("Bilgileri Düzenle");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        sifredegis_button.setBackground(new java.awt.Color(215, 38, 49));
        sifredegis_button.setLabel("Şifre Değiştirme");
        sifredegis_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifredegis_buttonActionPerformed(evt);
            }
        });

        ad_degis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_degisActionPerformed(evt);
            }
        });

        sehir_degis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Kayseri", "Karabük", "Konya", "Zonguldak" }));
        sehir_degis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehir_degisActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(162, 213, 198));
        jLabel8.setText("Mevcut Şifre:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(162, 213, 198));
        jLabel9.setText("Yeni Şifre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(162, 213, 198));
        jLabel10.setText("Yeni Şifre Tekrar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personelSoyad)
                            .addComponent(personelSehir)
                            .addComponent(personelAd)
                            .addComponent(personelNo))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ad_degis)
                            .addComponent(soyad_degis)
                            .addComponent(sehir_degis, 0, 179, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yeniSifre)
                            .addComponent(mevcutSifre)
                            .addComponent(tekrarYeniSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(sifredegis_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(personelAd)
                        .addComponent(ad_degis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(personelSoyad)
                    .addComponent(soyad_degis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personelSehir)
                    .addComponent(sehir_degis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(personelNo))
                .addGap(30, 30, 30)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mevcutSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tekrarYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(sifredegis_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(7, 123, 138));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numara", "İsim", "Soyisim", "Cinsiyet", "Şehir", "İlçe", "Fatura Miktarı", "Fatura Süresi", "Aktiflik"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(162, 213, 198));
        jLabel7.setText("Şehrinizdeki Müşteriler");

        fatura_button.setActionCommand("Fatura Ekle");
        fatura_button.setBackground(new java.awt.Color(215, 38, 49));
        fatura_button.setLabel("Fatura Ekle");
        fatura_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatura_buttonActionPerformed(evt);
            }
        });

        musteri_ekle.setActionCommand("Müşteri Ekle");
        musteri_ekle.setBackground(new java.awt.Color(215, 38, 49));
        musteri_ekle.setLabel("Müşteri Ekle");
        musteri_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteri_ekleActionPerformed(evt);
            }
        });

        musteri_sil.setActionCommand("Müşteri Sil");
        musteri_sil.setBackground(new java.awt.Color(215, 38, 49));
        musteri_sil.setLabel("Müşteri Sil");
        musteri_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteri_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(fatura_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(musteri_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(musteri_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatura_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteri_ekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteri_sil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        cikis_yap.setActionCommand("Çıkış Yap");
        cikis_yap.setBackground(new java.awt.Color(215, 38, 49));
        cikis_yap.setLabel("Çıkış Yap");
        cikis_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_yapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cikis_yap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cikis_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int button1_selection = 0;
    //int count_of_employees = 0;
    String plaka;
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
         if(button1_selection == 0){
             button1_selection++;
             ad_degis.setVisible(true);
             ad_degis.setText(personel_isim);
             soyad_degis.setVisible(true);
             soyad_degis.setText(personel_soyisim);
             sehir_degis.setVisible(true);
             if(personelSehir.getText() == "Ankara")
                 sehir_degis.setSelectedIndex(0);
             else if(personelSehir.getText() == "Kayseri")
                 sehir_degis.setSelectedIndex(1);
             else if(personelSehir.getText() == "Karabük")
                 sehir_degis.setSelectedIndex(2);
             else if(personelSehir.getText() == "Konya")
                 sehir_degis.setSelectedIndex(3);
             else if(personelSehir.getText() == "Zonguldak")
                 sehir_degis.setSelectedIndex(4);
             button1.setLabel("Bilgileri Onayla");
         }
         else if(button1_selection == 1){
             if(ad_degis.getText().isEmpty() || soyad_degis.getText().isEmpty()){
                 JOptionPane.showMessageDialog(this,"İsim veya soyisim kısmı boş bırakılamaz!");
             }
             else{
             personel_isim = ad_degis.getText();
             personel_soyisim = soyad_degis.getText();
             if(sehir_degis.getSelectedIndex() == 0){
                 sehir = "Ankara";
                 plaka = "06";
             }else if(sehir_degis.getSelectedIndex() == 1){
                 sehir = "Kayseri";
                 plaka = "38";
             }else if(sehir_degis.getSelectedIndex() == 2){
                 sehir = "Karabük";
                 plaka = "78";
             }else if(sehir_degis.getSelectedIndex() == 3){
                 sehir = "Konya";
                 plaka = "42";
             }else if(sehir_degis.getSelectedIndex() == 4){
                 sehir = "Zonguldak";
                 plaka = "67";
             }
             
            /*try {
            pst = con.prepareStatement("select * from \"SYSTEM\".PERSONEL where pCity = ?");
            pst.setString(1, sehir);
            rs = pst.executeQuery();
            while(rs.next())
                count_of_employees++;
            }catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Buraya bak kardeşim");
            }*/
            
            try{
            String msql = "update personel set pFName = ?, pLName = ?, pCity = ? where personelNo = ?";
            pst = con.prepareStatement(msql);
            pst.setString(1, personel_isim);
            pst.setString(2, personel_soyisim);
            pst.setString(3, sehir);
            pst.setString(4, no);
            pst.executeUpdate();
            }catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 311111");
            }
             /*
            try {
           
            String s = String.format("%02d",(count_of_employees + 1));
            no = plaka + s;
            String msql = "update personel set personelNo = ? where pFName = ?, pLName = ?, pCity = ?, pSifre = ?";
            pst = con.prepareStatement(msql);
            pst.setString(1, no);
            pst.setString(2, personel_isim);
            pst.setString(3, personel_soyisim);
            pst.setString(4, sehir);
            pst.setString(5, sifre);
            pst.executeUpdate();
            
            }catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hayır buraya bak sıkıntı burada");
            }
             */
             
             button1_selection--;
             ad_degis.setVisible(false);
             soyad_degis.setVisible(false);
             sehir_degis.setVisible(false);
             button1.setLabel("Bilgileri Düzenle");
             PersonelEkran yenipersonelekran = new PersonelEkran(personel_isim,personel_soyisim,cinsiyet,sehir,no,sifre);
             this.dispose();
             yenipersonelekran.setVisible(true);
             }
         }
    }//GEN-LAST:event_button1ActionPerformed

    private void sehir_degisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehir_degisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehir_degisActionPerformed

    private void ad_degisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_degisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_degisActionPerformed
    int sifredegisbutton_choice = 0;
    private void sifredegis_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifredegis_buttonActionPerformed
        if(mevcutSifre.getText().equals(sifre)){
                if(yeniSifre.getText().equals(tekrarYeniSifre.getText())){
                    sifre = yeniSifre.getText();
                    try{
                    String msql = "update personel set pSifre = ? where personelNo = ?";
                     pst = con.prepareStatement(msql);
                    pst.setString(1, sifre);
                    pst.setString(2, no);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Şifreniz başarıyla yenilenmiştir.");
                    PersonelEkran yenipersonelekran = new PersonelEkran(personel_isim,personel_soyisim,cinsiyet,sehir,no,sifre);
                     this.dispose();
                    yenipersonelekran.setVisible(true);
                    }catch (SQLException ex) {
                     Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("Hata Burada 311111");
                    }
                }else
                    JOptionPane.showMessageDialog(this,"Yeni şifre ve tekrarı aynı olmalıdır.");
                
            }else{
                System.out.println(sifre + " " + mevcutSifre.getText());
                JOptionPane.showMessageDialog(this,"Mevcut şifre yanlış girilmiştir.");}
    }//GEN-LAST:event_sifredegis_buttonActionPerformed

    private void fatura_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatura_buttonActionPerformed
        FaturaEkle faturaekle = new FaturaEkle(musteri_no,musteri_isim, musteri_soyisim,musteri_cins,musteri_sehir,musteri_ilce,musteri_faturaMiktar,musteri_faturaZaman,musteri_aktifMi,personel_isim,personel_soyisim,cinsiyet,sehir,no,sifre);
        faturaekle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fatura_buttonActionPerformed
    String musteri_no,musteri_isim, musteri_soyisim,musteri_cins,musteri_sehir,musteri_ilce,musteri_faturaMiktar,musteri_faturaZaman,musteri_aktifMi;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel d1 = (DefaultTableModel) jTable2.getModel();
         int SelectIndex = jTable2.getSelectedRow();
         this.musteri_no = d1.getValueAt(SelectIndex,0).toString();
         this.musteri_isim = d1.getValueAt(SelectIndex,1).toString();
         this.musteri_soyisim = d1.getValueAt(SelectIndex,2).toString();
         this.musteri_cins = d1.getValueAt(SelectIndex,3).toString();
         this.musteri_sehir = d1.getValueAt(SelectIndex,4).toString();
         this.musteri_ilce = d1.getValueAt(SelectIndex,5).toString();
         if(d1.getValueAt(SelectIndex,6).toString() != null)
             this.musteri_faturaMiktar = d1.getValueAt(SelectIndex,6).toString();
         if(d1.getValueAt(SelectIndex, 7).toString() != null)
             this.musteri_faturaZaman = d1.getValueAt(SelectIndex, 7).toString();
         this.musteri_aktifMi = d1.getValueAt(SelectIndex, 8).toString();
         System.out.println(musteri_no);
    }//GEN-LAST:event_jTable2MouseClicked

    private void musteri_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteri_ekleActionPerformed
        MusteriEkle musteriekle = new MusteriEkle(personel_isim,personel_soyisim,cinsiyet,sehir,no,sifre);
        musteriekle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_musteri_ekleActionPerformed

    private void musteri_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteri_silActionPerformed
            
        if(musteri_no == null){
            JOptionPane.showMessageDialog(this,"Lütfen müşteri seçiniz.");
        }else{
         try{
            String msql = "delete from musteri where clientNo = ? ";
            pst = con.prepareStatement(msql);
            pst.setString(1, musteri_no);
            pst.executeUpdate();
            PersonelEkran yenipersonelekran = new PersonelEkran(personel_isim,personel_soyisim,cinsiyet,sehir,no,sifre);
             this.dispose();
             yenipersonelekran.setVisible(true);
            }catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 311111");
            }
        }
    }//GEN-LAST:event_musteri_silActionPerformed

    private void cikis_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_yapActionPerformed
        Giris giris = new Giris();
        giris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cikis_yapActionPerformed
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_degis;
    private java.awt.Button button1;
    private java.awt.Button cikis_yap;
    private java.awt.Button fatura_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPasswordField mevcutSifre;
    private java.awt.Button musteri_ekle;
    private java.awt.Button musteri_sil;
    private javax.swing.JLabel personelAd;
    private javax.swing.JLabel personelNo;
    private javax.swing.JLabel personelSehir;
    private javax.swing.JLabel personelSoyad;
    private javax.swing.JComboBox<String> sehir_degis;
    private java.awt.Button sifredegis_button;
    private javax.swing.JTextField soyad_degis;
    private javax.swing.JPasswordField tekrarYeniSifre;
    private javax.swing.JPasswordField yeniSifre;
    // End of variables declaration//GEN-END:variables
}
